export enum Tags {
    Innenraum = "Innenraum",
    Aussenraum = "Außenraum",
    RepraesentativStadt = "Repräsentativ Stadt",
    RepraesentativQuartier = "Repräsentativ Quartier",
    nichtRepraesentativ = "Nicht Repräsentativ",
    ZielgruppeSenioren = "Zielgruppe Senioren",
    ZielgruppeKinder = "Zielgruppe Kinder",
    ZielgruppeJungeErwachsene = "Zielgruppe junge Erwachsene",
    Eingeschossig = "Eingeschossig",
    Geschossuebergreifend = "Geschossuebergreifend",
    Stapelbar = "Stapelbar",
    CashCow = "Cash Cow",
    Rentabel = "Rentabel",
    Selbsttragend = "Selbsttragend",
    Finanzierungsbedarf = "Finanzierungsbedarf",
    KulturelleEinrichtung = "Kulturelle Einrichtung",
    Bildungseinrichtung = "Bildungseinrichtung",
    SozialeEinrichtung = "Soziale Einrichtung",
    Wohnraumnutzung = "Wohnraumnutzung",
    SportNutzung = "SportNutzung",
    ErfordertLicht = "Erfordert Licht",
    ErfordertKeinLicht = "Erfordert kein Licht",
    Infrastruktur = "Infrastruktur",
    IndustrieUndHandel = "Industrie und Handel",
    PublikumsMagnet = "Publikumsmagnet",
    KonstantesPublikum = "konstantes Publikum",
    KeinPublikum = "kein Publikum",
    Konsumfrei = "Konsumfrei",
    Gesundheit = "Gesundheit",
    Begegnungsort = "Begegnungsort",
    oekologisch = "oekologisch",


}
